### ISSUE TITLE
Sometime the title isn't visible when the user unmaximize windows

### ISSUE THREAD

**Issue by cedryc** [cedryc/xfwm4#2]
This bug only occurs only in special cases, when the application start maximized.

Steps to reproduce:
1) open an application and maximize it.
2) then close it and restart it. The window should be maximized
3) unmaximize the window.

The title should be displayed behind the top panel or out of the screen.

**Comment by FedeDP** [comment]
Ok, i've got this bug too. It did not happened in thunar, but in geany it appeared.
I guess it can be a bug with gtk2: geany uses gtk2, and the bug occurs, while instead in thunar-git (built together exo-git and libxce4ui/util-git with --enable-gtk3, so i guess it uses gtk3) it didn't.

**Comment by cedryc** [comment]
@FedeDP thanks for testing!
For information this bug was related to xfwm4-titleless branch, nothing to do with gtk.

**Comment by FedeDP** [comment]
Nice to hear this!
Thanks for your work!
