### ISSUE TITLE
4.11.3-t corner tiling with maximize on move

### ISSUE THREAD

**Issue by FedeDP** [cedryc/xfwm4#5]
Hi! 
Your latest update is very good, i really like it.
I'm just having a little problem:  the new option to "maximize on move toward the top edge" breaks corner tiling. It should be better if they could co-exhist.
Something like 90% of top space will call maximize, and 5% left /right will call corner tiling.
I don't know if this is a bug or a feature.

Btw really thanks for your work, i really appreciate it. It is getting better and better ;)

**Comment by cedryc** [comment]
hello,

This is an expected behaviour. I do this because maximize on move to edge break Top tiling and add corner tilling without top tiling does not make much sense to me...
That can be eventually changed.

**Comment by FedeDP** [comment]
As I thought, that was not a bug!
I don't know, i just feel it would be better to still have corner tiling, otherwise user would lost bottom corner tiling too. Tell me if i'm wrong!
But may be i'm the only one who cares here, in which case i should not be considered :)

**Comment by cedryc** [comment]
Yes maybe you are right. I did not pay much attention to it because don't use maximize option.
I will probably change it.

**Comment by FedeDP** [comment]
Thanks!

**Comment by cedryc** [comment]
done in v4.11.4!
